# Generated by Powerlevel10k configuration wizard on 2026-05-06 at 14:50 -03.
# Based on romkatv/powerlevel10k/config/p10k-lean.zsh, checksum 02674.
# Wizard options: nerdfont-v3 + powerline, small icons, unicode, lean, 1 line, compact,
# many icons, fluent, transient_prompt, instant_prompt=verbose.

'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
  emulate -L zsh -o extended_glob

  unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'

  [[ $ZSH_VERSION == (5.<1->*|<6->.*) ]] || return

  # Elementos do prompt originais
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    os_icon                 # os identifier
    dir                     # current directory
    vcs                     # git status
    prompt_char             # prompt symbol
  )

  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    status                  # exit code of the last command
    command_execution_time  # duration of the last command
    background_jobs         # presence of background jobs
    direnv                  # direnv status
    asdf                    # asdf version manager
    virtualenv              # python virtual environment
    anaconda                # conda environment
    pyenv                   # python environment
    goenv                   # go environment
    nodenv                  # node.js version from nodenv
    nvm                     # node.js version from nvm
    nodeenv                 # node.js environment
    rbenv                   # ruby version from rbenv
    rvm                     # ruby version from rvm
    fvm                     # flutter version management
    luaenv                  # lua version from luaenv
    jenv                    # java version from jenv
    plenv                   # perl version from plenv
    perlbrew                # perl version from perlbrew
    phpenv                  # php version from phpenv
    scalaenv                # scala version from scalaenv
    haskell_stack           # haskell version from stack
    kubecontext             # current kubernetes context
    terraform               # terraform workspace
    aws                     # aws profile
    aws_eb_env              # aws elastic beanstalk environment
    azure                   # azure account name
    gcloud                  # google cloud cli account and project
    google_app_cred         # google application credentials
    toolbox                 # toolbox name
    context                 # user@hostname
    nordvpn                 # nordvpn connection status
    ranger                  # ranger shell
    yazi                    # yazi shell
    nnn                     # nnn shell
    lf                      # lf shell
    xplr                    # xplr shell
    vim_shell               # vim shell indicator
    midnight_commander      # midnight commander shell
    nix_shell               # nix shell
    chezmoi_shell           # chezmoi shell
    todo                    # todo items
    timewarrior             # timewarrior tracking status
    taskwarrior             # taskwarrior task count
    per_directory_history   # local/global indicator
  )

  # Configurações visuais originais
  typeset -g POWERLEVEL9K_MODE=nerdfont-v3
  typeset -g POWERLEVEL9K_ICON_PADDING=none
  typeset -g POWERLEVEL9K_BACKGROUND=
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_{LEFT,RIGHT}_WHITESPACE=
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SUBSEGMENT_SEPARATOR=' '
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SEGMENT_SEPARATOR=
  typeset -g POWERLEVEL9K_ICON_BEFORE_CONTENT=true
  typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=false

  # OS Icon e Prompt Char
  typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=76
  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=196
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='❯'

  # Directory
  typeset -g POWERLEVEL9K_DIR_FOREGROUND=31
  typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
  typeset -g POWERLEVEL9K_DIR_ANCHOR_BOLD=true

  #####################################[ vcs: git status ]######################################
  # Ícones nativos (Substituindo a função manual my_git_formatter)
  typeset -g POWERLEVEL9K_VCS_BRANCH_ICON='\uF126 '
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON='?'

  # Desativamos a formatação customizada (Lean default) para habilitar os ícones nativos
  typeset -g POWERLEVEL9K_VCS_DISABLE_GITSTATUS_FORMATTING=false
  
  # Força a exibição do ícone do Git/Github antes do status
  typeset -g POWERLEVEL9K_VCS_VISUAL_IDENTIFIER_EXPANSION='${P9K_VISUAL_IDENTIFIER}'
  
  # Habilita os ícones de status dinâmicos
  typeset -g POWERLEVEL9K_VCS_STAGED_ICON='●'
  typeset -g POWERLEVEL9K_VCS_UNSTAGED_ICON='!'
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON='?'
  typeset -g POWERLEVEL9K_VCS_COMMITS_AHEAD_ICON='⇡'
  typeset -g POWERLEVEL9K_VCS_COMMITS_BEHIND_ICON='⇣'

  typeset -g POWERLEVEL9K_VCS_BACKENDS=(git)
  typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=76
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=76
  typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=178

  ##############################################################################################

  # Status e Execution Time originais
  typeset -g POWERLEVEL9K_STATUS_EXTENDED_STATES=true
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=0
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=101
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT='d h m s'
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PREFIX='%ftook '

  # Configurações de comportamento originais
  typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=always
  typeset -g POWERLEVEL9K_INSTANT_PROMPT=verbose
  typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=true

  (( ! $+functions[p10k] )) || p10k reload
}

typeset -g POWERLEVEL9K_CONFIG_FILE=${${(%):-%x}:a}
(( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
'builtin' 'unset' 'p10k_config_opts'
